name: Publish on CurseForge & Modrinth    #The name of your GitHub Action on github.com

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}

permissions:
  contents: write

jobs:
  build-20:
    runs-on: ubuntu-latest
    env:
      MINECRAFT_VERSION: 1.20.1
      JAVA_VERSION: 17
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build

      - name: Publish to Curseforge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          dependencies: |
            farmers-delight(required){modrinth:farmers-delight}{curseforge:398521}
            croptopia(required){curseforge:415438}#(ignore:modrinth)
            lmft(required){modrinth:lmft}{curseforge:656346}
            endersdelight(optional){modrinth:enders-delight}{curseforge:827163}
            nethersdelight(optional){modrinth:nethers-delight}{curseforge:496394}
            seeddelight(optional){modrinth:seed-delight}{curseforge:1016377}
            delightful(optional){modrinth:delightful}{curseforge:637529}
            rusticdelight(optional){modrinth:rustic-delight}{curseforge:1106612}

          curseforge-id: 1132546
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: nyIn6Lmk
          modrinth-token: "${{env.MODRINTH_TOKEN}}"


          version-type: release

          loaders: forge
